CREATE TABLE IF NOT EXISTS attendance_events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  legacy_worship_weekend_id INTEGER UNIQUE,
  event_date DATE NOT NULL,
  title TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_attendance_events_event_date ON attendance_events(event_date);
CREATE INDEX IF NOT EXISTS idx_attendance_events_legacy ON attendance_events(legacy_worship_weekend_id);

CREATE TABLE IF NOT EXISTS attendance_types (
  id INTEGER PRIMARY KEY,
  name TEXT NOT NULL,
  is_area_based BOOLEAN NOT NULL DEFAULT false,
  active_weekdays SMALLINT[] NOT NULL DEFAULT '{}',
  is_active BOOLEAN NOT NULL DEFAULT true,
  sort_order INTEGER NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS attendance_records (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  legacy_record_id INTEGER UNIQUE,
  event_id BIGINT NOT NULL REFERENCES attendance_events(id) ON DELETE CASCADE,
  member_id INTEGER NOT NULL REFERENCES pastoral_members(id),
  attendance_type_id INTEGER NOT NULL REFERENCES attendance_types(id),
  attendance_mode TEXT NOT NULL DEFAULT 'physical' CHECK (attendance_mode IN ('physical', 'online')),
  recorded_at TIMESTAMPTZ,
  source_system TEXT NOT NULL DEFAULT 'legacy_mssql',
  source_id TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_attendance_records_event_type ON attendance_records(event_id, attendance_type_id);
CREATE INDEX IF NOT EXISTS idx_attendance_records_member_event ON attendance_records(member_id, event_id);
CREATE INDEX IF NOT EXISTS idx_attendance_records_type_member ON attendance_records(attendance_type_id, member_id);
CREATE INDEX IF NOT EXISTS idx_attendance_records_recorded_at ON attendance_records(recorded_at);
CREATE INDEX IF NOT EXISTS idx_attendance_records_source ON attendance_records(source_system, source_id);

CREATE OR REPLACE VIEW attendance_record_dedup AS
SELECT DISTINCT ON (event_id, member_id, attendance_type_id)
  id,
  legacy_record_id,
  event_id,
  member_id,
  attendance_type_id,
  attendance_mode,
  recorded_at,
  source_system,
  source_id,
  created_at,
  updated_at
FROM attendance_records
ORDER BY event_id, member_id, attendance_type_id, recorded_at NULLS LAST, id;
