BEGIN;

CREATE TABLE IF NOT EXISTS countries (
  id integer PRIMARY KEY,
  code text NOT NULL UNIQUE,
  name text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS regions (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  country_id integer NOT NULL REFERENCES countries(id),
  city text NOT NULL,
  district text,
  postal_code text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (country_id, city, district, postal_code)
);

CREATE TABLE IF NOT EXISTS churches (
  id integer PRIMARY KEY,
  code text UNIQUE,
  name text NOT NULL,
  church_type text NOT NULL DEFAULT '本會',
  country_id integer REFERENCES countries(id),
  region_id integer REFERENCES regions(id),
  phone text,
  address text,
  tax_id text,
  is_active boolean NOT NULL DEFAULT true,
  sort_order integer NOT NULL DEFAULT 0,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS membership_categories (
  code text PRIMARY KEY,
  name text NOT NULL,
  is_member boolean NOT NULL DEFAULT false,
  is_external boolean NOT NULL DEFAULT false,
  sort_order integer NOT NULL DEFAULT 0,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS professions (
  id integer PRIMARY KEY,
  name text NOT NULL,
  sort_order integer NOT NULL DEFAULT 0,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS pastoral_titles (
  id integer PRIMARY KEY,
  name text NOT NULL,
  sort_order integer NOT NULL DEFAULT 0,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS marital_statuses (
  id integer PRIMARY KEY,
  name text NOT NULL,
  is_married boolean NOT NULL DEFAULT false,
  sort_order integer NOT NULL DEFAULT 0,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS pastoral_group_types (
  id integer PRIMARY KEY,
  name text NOT NULL,
  sort_order integer NOT NULL DEFAULT 0,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS pastoral_groups (
  id integer PRIMARY KEY,
  church_id integer REFERENCES churches(id),
  parent_id integer REFERENCES pastoral_groups(id),
  group_type_id integer REFERENCES pastoral_group_types(id),
  level_no integer NOT NULL DEFAULT 0,
  name text NOT NULL,
  path text,
  is_active boolean NOT NULL DEFAULT true,
  sort_order integer NOT NULL DEFAULT 0,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS pastoral_group_closure (
  ancestor_id integer NOT NULL REFERENCES pastoral_groups(id) ON DELETE CASCADE,
  descendant_id integer NOT NULL REFERENCES pastoral_groups(id) ON DELETE CASCADE,
  depth integer NOT NULL,
  PRIMARY KEY (ancestor_id, descendant_id)
);

CREATE TABLE IF NOT EXISTS pastoral_members (
  id integer PRIMARY KEY,
  church_id integer REFERENCES churches(id),
  name text NOT NULL,
  gender integer,
  birthday date,
  membership_category_code text REFERENCES membership_categories(code),
  title_id integer REFERENCES pastoral_titles(id),
  profession_id integer REFERENCES professions(id),
  profession_note text,
  source_text text,
  marital_status_id integer REFERENCES marital_statuses(id),
  marital_note text,
  line_display_id text,
  line_user_id text,
  light_status integer,
  followup_staff_id integer,
  created_date date,
  baptized_date date,
  note text,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS pastoral_member_contacts (
  member_id integer PRIMARY KEY REFERENCES pastoral_members(id) ON DELETE CASCADE,
  email text,
  home_phone text,
  office_phone text,
  mobile_phone text,
  preferred_contact_time text,
  referrer_name text,
  referrer_phone text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS pastoral_member_addresses (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  member_id integer NOT NULL REFERENCES pastoral_members(id) ON DELETE CASCADE,
  country_id integer REFERENCES countries(id),
  region_id integer REFERENCES regions(id),
  postal_code text,
  city text,
  district text,
  address_line text,
  is_primary boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS pastoral_member_faith (
  member_id integer PRIMARY KEY REFERENCES pastoral_members(id) ON DELETE CASCADE,
  is_christian boolean,
  previous_church_id integer REFERENCES churches(id),
  previous_church_text text,
  willing_join_church boolean,
  willing_contact boolean,
  accepted_christ boolean,
  willing_continue_group boolean,
  willing_baptism boolean,
  prayer_request text,
  feedback text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS pastoral_member_group_assignments (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  member_id integer NOT NULL REFERENCES pastoral_members(id) ON DELETE CASCADE,
  group_id integer NOT NULL REFERENCES pastoral_groups(id),
  role_name text,
  started_at date,
  ended_at date,
  is_current boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (member_id, group_id, is_current)
);

CREATE TABLE IF NOT EXISTS pastoral_group_leaders (
  id integer PRIMARY KEY,
  group_id integer NOT NULL REFERENCES pastoral_groups(id) ON DELETE CASCADE,
  member_id integer REFERENCES pastoral_members(id),
  title_id integer REFERENCES pastoral_titles(id),
  is_current boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS pastoral_care_records (
  id integer PRIMARY KEY,
  member_id integer NOT NULL REFERENCES pastoral_members(id) ON DELETE CASCADE,
  staff_id integer,
  care_at timestamptz,
  content text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS relationship_types (
  id integer PRIMARY KEY,
  name text NOT NULL,
  reverse_name text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS pastoral_member_relationships (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  member_id integer NOT NULL REFERENCES pastoral_members(id) ON DELETE CASCADE,
  related_member_id integer NOT NULL REFERENCES pastoral_members(id) ON DELETE CASCADE,
  relationship_type_id integer NOT NULL REFERENCES relationship_types(id),
  note text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CHECK (member_id <> related_member_id),
  UNIQUE (member_id, related_member_id, relationship_type_id)
);

CREATE TABLE IF NOT EXISTS pastoral_member_family_notes (
  member_id integer PRIMARY KEY REFERENCES pastoral_members(id) ON DELETE CASCADE,
  spouse_text text,
  father_text text,
  mother_text text,
  children_text text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS pastoral_member_files (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  member_id integer NOT NULL REFERENCES pastoral_members(id) ON DELETE CASCADE,
  file_type text NOT NULL,
  file_name text NOT NULL,
  storage_path text NOT NULL,
  mime_type text,
  file_size integer,
  file_data bytea,
  file_id uuid REFERENCES files(file_id) ON DELETE SET NULL,
  uploaded_by_staff_id text,
  uploaded_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_pastoral_member_files_member_type
  ON pastoral_member_files (member_id, file_type, uploaded_at DESC);

CREATE INDEX IF NOT EXISTS idx_pastoral_member_files_file_id
  ON pastoral_member_files (file_id);

CREATE TABLE IF NOT EXISTS baptism_events (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL,
  baptism_date date NOT NULL,
  note text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS baptism_participants (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  baptism_event_id integer NOT NULL REFERENCES baptism_events(id) ON DELETE CASCADE,
  member_id integer NOT NULL REFERENCES pastoral_members(id) ON DELETE CASCADE,
  completed_baptism_class boolean NOT NULL DEFAULT false,
  certificate_photo_file_id uuid REFERENCES pastoral_member_files(id),
  completed_baptism boolean NOT NULL DEFAULT false,
  note text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (baptism_event_id, member_id)
);

CREATE INDEX IF NOT EXISTS idx_pastoral_members_name ON pastoral_members (name);
CREATE INDEX IF NOT EXISTS idx_pastoral_members_church ON pastoral_members (church_id);
CREATE INDEX IF NOT EXISTS idx_pastoral_members_category ON pastoral_members (membership_category_code);
CREATE INDEX IF NOT EXISTS idx_pastoral_members_line_user ON pastoral_members (line_user_id);
CREATE INDEX IF NOT EXISTS idx_pastoral_groups_parent ON pastoral_groups (parent_id);
CREATE INDEX IF NOT EXISTS idx_pastoral_assignments_member ON pastoral_member_group_assignments (member_id);
CREATE INDEX IF NOT EXISTS idx_pastoral_assignments_group ON pastoral_member_group_assignments (group_id);
CREATE INDEX IF NOT EXISTS idx_pastoral_care_member ON pastoral_care_records (member_id);

COMMIT;
